name: Run BigQuery Summary

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ Every hour on the hour
  workflow_dispatch:       # 🧑‍💻 Manual trigger

jobs:
  bigquery-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: deft-advice-459518-c8

      - name: Run SQL query
        run: |
          set -e
          echo "Running query..."
          mkdir -p data
          bq query --use_legacy_sql=false --format=csv < sql/hourly_event_summary.sql > data/daily_event_summary.csv
