name: Run BigQuery Summary

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ Every hour on the hour
  workflow_dispatch:       # 🧑‍💻 Manual trigger

jobs:
  bigquery-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: deft-advice-459518-c8

      - name: Run SQL query
        run: |
          set -e
          echo "Running query..."
          mkdir -p data
          bq query --use_legacy_sql=false --format=csv < sql/hourly_event_summary.sql > data/daily_event_summary.csv

      - name: Commit and push results
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/daily_event_summary.csv
          git commit -m "Update daily_event_summary.csv" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

